// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsPp-d3a1c9CEvLtopgL2W6E558ODy3FE',
    appId: '1:998366769861:web:85746c84be869a25d076ac',
    messagingSenderId: '998366769861',
    projectId: 'ai-master-43e94',
    authDomain: 'ai-master-43e94.firebaseapp.com',
    databaseURL: 'https://ai-master-43e94-default-rtdb.firebaseio.com',
    storageBucket: 'ai-master-43e94.appspot.com',
    measurementId: 'G-GN9XBFHGFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlBJoIY8RqrOhXJRx3xH30aKSMsEghxt8',
    appId: '1:998366769861:android:4e91a6c536224687d076ac',
    messagingSenderId: '998366769861',
    projectId: 'ai-master-43e94',
    databaseURL: 'https://ai-master-43e94-default-rtdb.firebaseio.com',
    storageBucket: 'ai-master-43e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsHREL6ngMekAwxljg53VB98cTNfE-tMk',
    appId: '1:998366769861:ios:9ce772ffcb048fe8d076ac',
    messagingSenderId: '998366769861',
    projectId: 'ai-master-43e94',
    databaseURL: 'https://ai-master-43e94-default-rtdb.firebaseio.com',
    storageBucket: 'ai-master-43e94.appspot.com',
    iosBundleId: 'com.example.createAiGenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsHREL6ngMekAwxljg53VB98cTNfE-tMk',
    appId: '1:998366769861:ios:9ce772ffcb048fe8d076ac',
    messagingSenderId: '998366769861',
    projectId: 'ai-master-43e94',
    databaseURL: 'https://ai-master-43e94-default-rtdb.firebaseio.com',
    storageBucket: 'ai-master-43e94.appspot.com',
    iosBundleId: 'com.example.createAiGenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsPp-d3a1c9CEvLtopgL2W6E558ODy3FE',
    appId: '1:998366769861:web:00d15c3a4fa3ed0dd076ac',
    messagingSenderId: '998366769861',
    projectId: 'ai-master-43e94',
    authDomain: 'ai-master-43e94.firebaseapp.com',
    databaseURL: 'https://ai-master-43e94-default-rtdb.firebaseio.com',
    storageBucket: 'ai-master-43e94.appspot.com',
    measurementId: 'G-40D56LYBLF',
  );

}